In [1]:
import torch
import numpy as np
from actor_critic_dynamic import ActorCritic_Dynamic, ContextDecoder


In [2]:
actor_critic  = ActorCritic_Dynamic(57,81,12,512,[256,128],[256,128],57*5,16,3,[128,64],0.0,'tanh',1.0)
decoder = ContextDecoder(19,[64,128],57,0.0)

In [3]:
model_path = "/home/oyoungquist/Research/LearningWBIC/genesis_lr_dreamwaq/logs/go1_dynamic/Dec25_22-49-15_config_test_26_gentletrade_dynrew_parpino_success/model_5000.pt"
loaded_model = torch.load(model_path,map_location='cpu')

In [6]:
actor_critic.load_state_dict(loaded_model['model_state_dict'])
decoder.load_state_dict(loaded_model['decoder_state_dict'])

<All keys matched successfully>

In [38]:
output_folder = "12_27_202508_21_32_no_pinn"
output_name = "no_pinn_epoch_499"

In [15]:
actor_critic.std_pos

Parameter containing:
tensor([0.9704, 0.9343, 0.9221, 0.9512, 0.9455, 0.9166, 0.9832, 0.9290, 0.9284,
        0.9700, 0.9282, 0.9242], requires_grad=True)

In [16]:
actor_critic.std_pos.data.fill_(1.0)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
actor_critic.std_pos

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)

In [18]:
actor_critic.std_tau

Parameter containing:
tensor([0.5116, 0.5606, 0.5219, 0.5112, 0.5607, 0.5260, 0.5087, 0.5606, 0.5455,
        0.5031, 0.5581, 0.5489], requires_grad=True)

In [21]:
actor_critic.std_tau.data.fill_(1.0)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
actor_critic.std_tau

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)

In [31]:
temp_load = torch.load("pretrained_models/dynamic/12_21_202521_14_56_no_pinn/no_pinn_epoch_499.pth")

In [32]:
temp_load.keys()

dict_keys(['action', 'decoder', 'options', 'optimizer_act', 'optimizer_enc', 'optimizer_decoder', 'act_lr_scheduler', 'decoder_lr_scheduler', 'enc_lr_scheduler', 'epoch'])

In [34]:
temp_load['action'] = actor_critic.state_dict()

In [36]:
temp_load['decoder'] = decoder.state_dict()

In [39]:
torch.save(temp_load, "pretrained_models/dynamic/12_27_202508_21_32_no_pinn/"+output_name)